#!/usr/bin/env python3
"""Regenerate radio_icon.h (window icon for roehre) from icons/retrowebradio.svg.
Needs python3-gi and the librsvg gdk-pixbuf loader. Run: python3 icons/mkicon.py"""
import os
import gi
gi.require_version("GdkPixbuf", "2.0")
from gi.repository import GdkPixbuf

SIZE = 64
here = os.path.dirname(os.path.realpath(__file__))
pb = GdkPixbuf.Pixbuf.new_from_file_at_size(os.path.join(here, "retrowebradio.svg"), SIZE, SIZE)
assert pb.get_has_alpha() and pb.get_n_channels() == 4
w, h, stride = pb.get_width(), pb.get_height(), pb.get_rowstride()
raw = pb.get_pixels()
data = b"".join(raw[y * stride:y * stride + w * 4] for y in range(h))

with open(os.path.join(here, "..", "radio_icon.h"), "w") as f:
    f.write("/* generated by icons/mkicon.py from icons/retrowebradio.svg, RGBA */\n")
    f.write("#define RADIO_ICON_W %d\n#define RADIO_ICON_H %d\n" % (w, h))
    f.write("static const unsigned char radio_icon_rgba[] = {\n")
    for i in range(0, len(data), 16):
        f.write("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n")
