#!/usr/bin/env python3
"""
Build logo.h (badge and signature for the radio cabinet) from the
Niethammer-Audio logo:

  python3 textures/mklogo.py [Niethammer-Audio.png]

The speaker shape and the signature are separated by colour, traced to
smooth vector outlines with potrace (this smooths the jagged lettering),
rendered again with anti-aliasing and stored as 8-bit alpha masks:
  logo_speaker / logo_sig : badge field, LOGO_W x LOGO_H
  sig_mask                : signature alone, SIG_W x SIG_H
Needs python3-pil, python3-gi (GdkPixbuf with the SVG loader) and potrace.
"""
import os, subprocess, sys, tempfile
import numpy as np
from PIL import Image, ImageFilter
import gi
gi.require_version("GdkPixbuf", "2.0")
from gi.repository import GdkPixbuf

LOGO_W, LOGO_H = 52, 54        # badge field (keeps the logo's 424:438 ratio)
SIG_H = 32                     # height of the signature below the keys

here = os.path.dirname(os.path.realpath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "..", "Niethammer-Audio.png")
a = np.asarray(Image.open(src).convert("RGB")).astype(int)
r, g, b = a[..., 0], a[..., 1], a[..., 2]
rows = np.arange(a.shape[0])[:, None]
# the lettering sits in rows 130..300; a light seam along the speaker's
# right edge elsewhere is not part of it
white = (r > 170) & (g > 170) & (b > 170) & (rows > 130) & (rows < 300)
red = (r > 150) & (g < 90) & (b < 90)
cols = np.arange(a.shape[1])[None, :]
speaker = ~red & (cols < 308)          # black body incl. the lettering on it

def trace(mask, alphamax):
    """mask -> smooth SVG (potrace) -> hi-res alpha array (4x)."""
    h, w = mask.shape
    with tempfile.TemporaryDirectory() as t:
        Image.fromarray(np.where(mask, 0, 255).astype(np.uint8)).convert("1").save(t + "/m.pbm")
        subprocess.run(["potrace", "-s", "-a", str(alphamax), "-O", "0.4", "-t", "4",
                        "-W", str(w), "-H", str(h), "-o", t + "/m.svg", t + "/m.pbm"], check=True)
        pb = GdkPixbuf.Pixbuf.new_from_file_at_size(t + "/m.svg", w * 4, h * 4)
    px = np.frombuffer(pb.get_pixels(), dtype=np.uint8)
    px = px.reshape(pb.get_height(), pb.get_rowstride())[:, :pb.get_width() * 4].reshape(
        pb.get_height(), pb.get_width(), 4)
    return px[..., 3]

def shrink(alpha, w, h):
    return np.asarray(Image.fromarray(alpha).resize((w, h), Image.LANCZOS))

spk = trace(speaker, 0.8)                     # keep the speaker's corners
sig = trace(white, 1.25)                      # round, smooth pen strokes
# a slightly broader pen, so the thin strokes survive the small sizes
sig = np.asarray(Image.fromarray(sig).filter(ImageFilter.MaxFilter(5)))

logo_speaker = shrink(spk, LOGO_W, LOGO_H)
logo_sig = shrink(sig, LOGO_W, LOGO_H)

ys, xs = np.nonzero(sig > 40)                 # signature bounding box
crop = sig[ys.min():ys.max() + 1, xs.min():xs.max() + 1]
SIG_W = round(crop.shape[1] * SIG_H / crop.shape[0])
sig_mask = shrink(crop, SIG_W, SIG_H)

def carray(name, arr):
    data = arr.astype(np.uint8).ravel()
    lines = ",\n".join("  " + ", ".join("%d" % v for v in data[i:i + 20])
                       for i in range(0, len(data), 20))
    return "static const unsigned char %s[] = {\n%s\n};\n" % (name, lines)

with open(os.path.join(here, "..", "logo.h"), "w") as f:
    f.write("/* generated by textures/mklogo.py from Niethammer-Audio.png: alpha masks */\n")
    f.write("#define LOGO_W %d\n#define LOGO_H %d\n#define SIG_W %d\n#define SIG_H %d\n"
            % (LOGO_W, LOGO_H, SIG_W, SIG_H))
    f.write(carray("logo_speaker", logo_speaker))
    f.write(carray("logo_sig", logo_sig))
    f.write(carray("sig_mask", sig_mask))
print("logo.h: badge %dx%d, signature %dx%d" % (LOGO_W, LOGO_H, SIG_W, SIG_H))
